language: java
jdk:
  - oraclejdk8
script:
  - ant -quiet build -Djavac.compilerargs=-nowarn -Dbuild.compiler.deprecation=false
  - ant -quiet test -Djavac.compilerargs=-nowarn -Dbuild.compiler.deprecation=false -Dtest.includes=NoTestsJustBuild
